platform :ios,'7.0'

target 'TYAlertView_Example' do
  pod 'TYAlertView', :path => '../'
  pod 'Masonry'
  # pod 'Reveal-SDK', :configurations => ['Debug']
  target 'TYAlertView_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
